### PR TITLE
Fix build error for Trebuchet 22.2

### PR DESCRIPTION
**Pull request by flame-0**
Updated patch from https://github.com/crdroidandroid/android_packages_apps_Launcher3/commit/d9d0440c7bcf4722762739a3dc6e97a1010afa4f
```
packages/apps/Trebuchet/quickstep/src/com/android/quickstep/TaskOverlayFactory.java:247: error: cannot find symbol
                    mTaskContainer.getThumbnailViewDeprecated().getTaskView().getRecentsView();
                                                               ^
  symbol:   method getTaskView()
  location: class TaskThumbnailViewDeprecated
1 error
```

### CODE REVIEW

**Comment by flame-0** [comment]
My friend told me you're already working on 22.2 fixes over email. Thanks for the heads-up! Since you're handling it, I'll close my PR now. Appreciate your efforts!
